#!/bin/sh
echo "Creating an SSH key for you..."
ssh-keygen -t rsa

echo "Installing xcode-stuff"
xcode-select --install

if ! command -v brew >/dev/null 2>&1; then
    echo "Installing Homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating Homebrew bundle"
    brew bundle --global
fi

echo "Installing Git..."
brew install git

echo "Configuring git..."
git config --global user.name "Jacob Patel"
git config --global user.email jseanpatel@gmail.com

echo "Installing other brew stuff..."
brew install tree
brew install wget
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
nvm install --lts

source ~/.bash_profile

echo "Installing CLI's"
npm i -g twilio-cli
npm i -g postcss-cli
npm i -g dotenv-cli
brew install gatsby-cli
brew install netlify-cli
brew install google-cloud-sdk
brew install mas

echo "Installing Eslint with Airbnb Style"
npm i eslint --save-dev
npm i eslint-config-airbnb --save-dev
npm i eslint-config-airbnb-base
npm i object.assign
npm i object.entries

echo "Installing Mac apps"
mas "Wipr", id: 1320666476

echo "Cleaning up brew"
brew cleanup

#Install Zsh & Oh My Zsh
echo "Installing Oh My ZSH..."
curl -L http://install.ohmyz.sh | sh

echo "Setting ZSH as shell..."
chsh -s /bin/zsh

# Apps
apps=(
  anki
  appcleaner
  bitwarden
  docker
  enpass
  figma
  firefox
  google-chrome
  intellij-idea
  iterm2
  nordvpn
  notion
  slack
  spotify
  sublime-merge
  sublime-text
  tableplus
  vscodium
  zoom
)

# Install apps to /Applications
# Default is: /Users/$user/Applications
echo "installing apps with Cask..."
brew install --appdir="/Applications" ${apps[@]}
brew cleanup

killall Finder

echo "----------------------------"
echo "Done with setup! Ready to go."
echo "----------------------------"
